### PR TITLE
Allow node-syslog to build under IO.js

### PR DESCRIPTION
**Pull request by jlabusch**
This model is probably not sustainable; we should move to something
like nan (https://github.com/iojs/nan).

### CODE REVIEW

**Comment by bnoordhuis** [comment]
It's a model that is perfectly sustainable and I say that as one of the maintainers of nan.  The issue seems to be that the compat shim hasn't been been updated in some time. @sam-github?

**Comment by jlabusch** [comment]
Isn't it better for projects like this to use a common set of shims? To keep that work in one place, and prevent exactly this kind of PR?

**Comment by bnoordhuis** [comment]
There is a canonical location for the compat shim, if that is what you mean, it's in our (StrongLoop's) strong-agent repository.  That's possibly not well advertised, though.

If your question is 'why not nan?', the compat shim is a lot leaner and - dare I say it? - better engineered.  It's not as all-encompassing as nan is but it covers all the needed functionality.

**Comment by jlabusch** [comment]
> If your question is 'why not nan?',

My real question was "why not a COMMON shim" -- I don't have any specific investment in nan.

I see that as of b1f30d06b in mid-Jan the strong-agent shim slightly changed its logic to NODE_VERSION_AT_LEAST(0, 11, 0) rather than matching specific major/minor version numbers, presumably to get around this exact issue?
If node-syslog had been able to use that compat shim in a more robust way than copy-paste, we'd be in a happy place right now.

**Comment by jlabusch** [comment]
Is there more work required here, or can this be merged?
Happy to tweak the version matching logic if needed.

**Comment by bnoordhuis** [comment]
I defer to @sam-github, he's done the most work on node-syslog lately.

**Comment by schamane** [comment]
Do we need to tag new version for this to package npm?

**Pull request merged**
