### PR TITLE
Use nan for node 4/5 compatibility

### PR DESCRIPTION
**Pull request by achingbrain**
Converts the project to use [nan](https://libraries.io/npm/nan) instead of the V8 APIs directly in order to fix the compilation issues for Node > 0.12 as reported in #51.

### CODE REVIEW

**Comment by achingbrain** [comment]
Oops, didn't see #49

**Comment by gmelika** [comment]
any plans on publishing this on npm soon?

**Comment by jeremycx** [comment]
I think everybody's left this pool and is now swimming with modern-syslog. It's 100% non-blocking, and is API compatible with node-syslog.

**Comment by achingbrain** [comment]
That's certainly what I'm doing.  Writing the PR was fun and all but modern-syslog appears to be the way to go.

**Comment by ultrafez** [comment]
Thanks for putting me onto modern-syslog, I hadn't come across it before now.

**Pull request closed without merging**
